name: Test deployment

on:
  pull_request:
    branches: [master]
    # paths: [website/**]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Test build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Test build example
        working-directory: website
        run: |
          yarn install --frozen-lockfile
          yarn build
